apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapp
spec:
  replicas: 2
  selector:
    matchLabels:
     app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: ashokit/javawebapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
   - port: 80
     targetPort: 8080

